name: Deploy

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  do-nothing:
    runs-on: ubuntu-latest  
    steps:
      - name: Nothing to do
        run: echo "This action does nothing"